// Extracts curated inline constant blocks from index.html into a standalone
// data file (data/curated-content.js) so index_v2.html can reuse all
// hand-written content without touching the original index.html.
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

// Extract a brace/bracket-balanced literal that follows `const NAME = `.
function extractConst(name, open, close) {
  const decl = `const ${name} = ${open}`;
  const start = src.indexOf(decl);
  if (start === -1) throw new Error(`Not found: ${name}`);
  let i = start + `const ${name} = `.length; // points at opening bracket
  let depth = 0, inStr = false, strCh = '', esc = false, inLineComment = false, inBlockComment = false;
  const from = i;
  for (; i < src.length; i++) {
    const c = src[i], n = src[i + 1];
    if (inLineComment) { if (c === '\n') inLineComment = false; continue; }
    if (inBlockComment) { if (c === '*' && n === '/') { inBlockComment = false; i++; } continue; }
    if (inStr) {
      if (esc) { esc = false; continue; }
      if (c === '\\') { esc = true; continue; }
      if (c === strCh) inStr = false;
      continue;
    }
    if (c === '/' && n === '/') { inLineComment = true; i++; continue; }
    if (c === '/' && n === '*') { inBlockComment = true; i++; continue; }
    if (c === '"' || c === "'" || c === '`') { inStr = true; strCh = c; continue; }
    if (c === open) depth++;
    else if (c === close) { depth--; if (depth === 0) { i++; break; } }
  }
  return src.slice(from, i);
}

const blocks = {
  IMAGE_FILES: ['{', '}'],
  COUNTRY_POINTS: ['{', '}'],
  CLADOGRAM_TREE: ['{', '}'],
  RICH_PROFILES: ['{', '}'],
  VALIDITY_STATUS: ['{', '}'],
  CLASSIFICATION_PATHS: ['{', '}'],
  FOSSIL_RECORDS: ['{', '}'],
  CURATED_EVIDENCE: ['{', '}'],
  MESO_PERIODS: ['[', ']'],
  EVENTS: ['[', ']'],
  PALEO_IMAGES: ['{', '}'],
};

const out = [];
out.push('// AUTO-GENERATED by tools/extract-curated.mjs from index.html.');
out.push('// Curated inline content extracted so index_v2.html can reuse it.');
out.push('// Do not edit by hand; re-run the extractor instead.');
out.push('(function(){');
out.push("const SOURCE_BASE = 'https://www.nhm.ac.uk/discover/dino-directory/';");
out.push("const DK_GUIDE_URL = 'https://www.nhm.ac.uk/discover/dinosaurs.html';");
out.push("function commonsImageUrl(file, width){ return 'https://commons.wikimedia.org/wiki/Special:FilePath/' + encodeURIComponent(String(file).replaceAll(' ', '_')) + '?width=' + width; }");
out.push("function commonsFilePage(file){ return 'https://commons.wikimedia.org/wiki/File:' + encodeURIComponent(String(file).replaceAll(' ', '_')); }");

for (const [name, [open, close]] of Object.entries(blocks)) {
  const body = extractConst(name, open, close);
  out.push(`const ${name} = ${body}; window.${name} = ${name};`);
}

// RICH_CONTENT is built via `const RICH_CONTENT = {...}` then several
// `Object.assign(RICH_CONTENT, {...})` batches. Capture the initial literal
// plus every Object.assign batch up to the AI merge loop.
function extractRichContent() {
  const startDecl = 'const RICH_CONTENT = {';
  const s = src.indexOf(startDecl);
  const initial = extractConst('RICH_CONTENT', '{', '}');
  const pieces = [initial];
  // find Object.assign(RICH_CONTENT, { ... }) batches
  const re = /Object\.assign\(RICH_CONTENT,\s*\{/g;
  re.lastIndex = s;
  let m;
  while ((m = re.exec(src))) {
    // balance from the opening brace of the object arg
    let i = m.index + m[0].length - 1; // at '{'
    let depth = 0, inStr = false, strCh = '', esc = false, lc = false, bc = false;
    const from = i;
    for (; i < src.length; i++) {
      const c = src[i], nx = src[i + 1];
      if (lc) { if (c === '\n') lc = false; continue; }
      if (bc) { if (c === '*' && nx === '/') { bc = false; i++; } continue; }
      if (inStr) { if (esc) { esc = false; continue; } if (c === '\\') { esc = true; continue; } if (c === strCh) inStr = false; continue; }
      if (c === '/' && nx === '/') { lc = true; i++; continue; }
      if (c === '/' && nx === '*') { bc = true; i++; continue; }
      if (c === '"' || c === "'" || c === '`') { inStr = true; strCh = c; continue; }
      if (c === '{') depth++;
      else if (c === '}') { depth--; if (depth === 0) { i++; break; } }
    }
    pieces.push(src.slice(from, i));
  }
  return pieces;
}

const richPieces = extractRichContent();
out.push(`window.RICH_CONTENT = ${richPieces[0]};`);
for (let k = 1; k < richPieces.length; k++) {
  out.push(`Object.assign(window.RICH_CONTENT, ${richPieces[k]});`);
}

out.push('})();');

const result = out.join('\n');
writeFileSync(new URL('../data/curated-content.js', import.meta.url), result);
console.log('Wrote data/curated-content.js —', (result.length / 1024).toFixed(0), 'KB');

// quick sanity: count top-level keys of each block by evaluating in a sandbox
console.log('RICH_CONTENT batches:', richPieces.length);
