#!/usr/bin/env python3
"""Fetch Wikipedia summaries for NHM-imported dinosaur entries that only have
a templated fallback description, and write data/wiki-enrichment.js.

Usage: python3 tools/fetch_wikipedia_enrichment.py
"""
import json
import re
import subprocess
import time
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NHM_FILE = ROOT / "data" / "nhm-imported-dinosaurs.js"
OUT_FILE = ROOT / "data" / "wiki-enrichment.js"

USER_AGENT = "DinosauriaWikiEnrichment/1.0 (personal hobby project; data enrichment script)"
TEMPLATE_MARKER = "NHM records fossils from"


def find_thin_entries():
    content = NHM_FILE.read_text()
    parts = re.split(r'\n  \[\n    "([a-z0-9-]+)",\n    "([^"]+)",\n', content)
    # parts[0] is header; then groups of (id, name, body)
    entries = []
    for i in range(1, len(parts), 3):
        slug, name, body = parts[i], parts[i + 1], parts[i + 2]
        if TEMPLATE_MARKER in body[:2000]:
            entries.append((slug, name))
    return entries


def fetch_summary(title):
    url = "https://en.wikipedia.org/api/rest_v1/page/summary/" + urllib.parse.quote(title.replace(" ", "_"))
    for attempt in range(4):
        proc = subprocess.run(
            ["curl", "-s", "-m", "10", "-w", "\n%{http_code}",
             "-H", f"User-Agent: {USER_AGENT}", url],
            capture_output=True, check=True,
        )
        out = proc.stdout.decode("utf-8")
        body, _, status = out.rpartition("\n")
        status = int(status)
        if status == 429:
            time.sleep(8 * (attempt + 1))
            continue
        if status == 404:
            return {"type": "not_found"}
        return json.loads(body)
    raise RuntimeError("rate limited after retries")


def main():
    entries = find_thin_entries()
    print(f"Found {len(entries)} thin entries")

    result = {}
    if OUT_FILE.exists():
        existing = OUT_FILE.read_text()
        m = re.search(r'=\s*(\{.*\});', existing, re.S)
        if m:
            result = json.loads(m.group(1))
            print(f"Resuming with {len(result)} already-resolved entries")

    failures = []

    for slug, name in entries:
        if slug in result:
            continue
        try:
            data = fetch_summary(name)
        except Exception as e:
            failures.append((slug, name, str(e)))
            time.sleep(1)
            continue

        if data.get("type") in ("disambiguation", "not_found"):
            failures.append((slug, name, data.get("type")))
            time.sleep(1)
            continue

        extract = data.get("extract", "").strip()
        page_url = data.get("content_urls", {}).get("desktop", {}).get("page", "")
        title = data.get("title", name)

        if not extract:
            failures.append((slug, name, "no extract"))
            time.sleep(1)
            continue

        result[slug] = {
            "extract": extract,
            "url": page_url,
            "title": title,
        }
        time.sleep(1)

    print(f"Resolved {len(result)} / {len(entries)}")
    if failures:
        print("Failures:")
        for slug, name, reason in failures:
            print(f"  {slug} ({name}): {reason}")

    out = "// Generated by tools/fetch_wikipedia_enrichment.py. Do not edit manually.\n"
    out += "window.WIKI_ENRICHMENT = " + json.dumps(result, indent=2, ensure_ascii=False) + ";\n"
    OUT_FILE.write_text(out)
    print(f"Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
